services:

    agent-server:
        container_name: agent-server
        image: nginx:1.27.4-alpine3.21
        working_dir: /app
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/app/public
        networks:
            - agent

    agent-fpm:
        image: agent-fpm
        pull_policy: never
        container_name: agent-fpm
        build: .
        volumes:
            - .:/app
        networks:
            - agent

networks:
    agent:
        driver: bridge
